### ISSUE TITLE
data_loader.py

### ISSUE THREAD

**Issue by nolehuan** [koyeongmin/PINet_new#21]
```
line419    x[j][y[j]<0] = -2
line420    x[j][y[j]>=self.p.y_size] = -2
```
why x ? maybe:
```
y[j][y[j]<0] = -2
y[j][y[j]>=self.p.y_size] = -2
```
???

and in agent.py
`line 99 while False ???`
line 127-129
```
if temp[i]>0:
         gt_one[temp==temp[i]] = 1            # same instance
         if temp[i] == 0:
```
???

where is the function get_angle_two_points quoted in util.py

so confusing

**Comment by koyeongmin** [comment]
1. Because TuSimple data set annotates 'x' values to '-2' when there is no traffic line at the position, I used 'x'.
2. These parts (line99, 127-129, get_angle_two_points) can be ignored. I forget to remove these parts after some experiments. 
Thank you, I will fix these points to make the code more readable.

**Comment by nolehuan** [comment]
thanks
